services:
  # 🚀 Backend Service - Express.js API Server
  - type: web
    name: cahit-firma-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false  # Manuel olarak Render dashboard'dan eklenecek
      - key: JWT_SECRET
        sync: false  # Manuel olarak Render dashboard'dan eklenecek
      - key: JWT_EXPIRE
        value: 7d
      - key: FRONTEND_URL
        value: https://cahit-firma-frontend.onrender.com
      - key: MAX_FILE_SIZE
        value: 50mb
      - key: UPLOAD_PATH
        value: ./uploads
      - key: RATE_LIMIT_WINDOW
        value: 15
      - key: RATE_LIMIT_MAX
        value: 100
    healthCheckPath: /api/health

  # 🎨 Frontend Service - React Web Service with SPA Routing
  - type: web
    name: cahit-firma-frontend
    env: node
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run serve
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: REACT_APP_API_URL
        value: https://cahit-firma-backend.onrender.com/api
      - key: GENERATE_SOURCEMAP
        value: false
    healthCheckPath: /health 